### ISSUE TITLE
`allowedDeviation` belongs to `node` in the Order schema?

### ISSUE THREAD

**Issue by ralienpp** [MaximilianRies/vd-m-a-5050#4]
The current version of the schema includes `allowedDeviation` as a mandatory attribute of a node: https://github.com/MaximilianRies/vd-m-a-5050/blob/5.0.0/order.schema#L66

However, the specification itself does not mention this attribute:
![image](https://user-images.githubusercontent.com/295338/94479942-d2ba0400-01d5-11eb-8394-435fef4222f0.png)

There are a several deviation-related attributes inside `nodePosition`, and they are correctly marked as optional (it coincides with the specification).

**Comment by MaximilianRies** [comment]
Hello Ralienpp,

sorry that it took me so long to get back to you, I wasn't entirely sure how things will be handled in the future.

First things first:
The development acitvities for this repository will cease. We will move over to a new repository that isn't tied to my personal credentials, but to a KIT-IFL Github account. This will ease the tranistion and onboarding of new members once I eventually leave the institute in the future.

As for your corrections:
You are completely right. I'll remove allowed deviation from the required list.
