### ISSUE TITLE
Instant action attribute name discrepancy

### ISSUE THREAD

**Issue by ralienpp** [MaximilianRies/vd-m-a-5050#5]
The schema for instant actions requires an `actionName` attribute: https://github.com/MaximilianRies/vd-m-a-5050/blob/5.0.0/instantActions.schema#L47

However, the specification does not contain such a field; though there is one called `actionType`, which is probably what is meant here.

@MaximilianRies, can you clarify which of these is correct?

**Comment by MaximilianRies** [comment]
Hello Ralienpp,

sorry that it took me so long to get back to you, I wasn't entirely sure how things will be handled in the future.

First things first:
The development acitvities for this repository will cease. We will move over to a new repository that isn't tied to my personal credentials, but to a KIT-IFL Github account. This will ease the tranistion and onboarding of new members once I leave the institute in the future.

As for your corrections:
actionType is the correct name of the field, you are right.
