### ISSUE TITLE
Invalid Json in order.schema (Version 5.0) line 298, position 421

### ISSUE THREAD

**Issue by henrydn** [MaximilianRies/vd-m-a-5050#6]
The wrong type of quote is used in order.schema (Version 5.0) line 298, position 42

`...rotationAllowed is “false", rotate before,...`

This means the document is invalid JSON, and breaks our attempts to generate models from the schema.

Looks like @ralienpp already created a PR for it. I just added this issue for visibility

**Comment by simonpfeiffer** [comment]
@MaximilianRies could you have a look and close the suggested PR?

**Comment by MaximilianRies** [comment]
Hello henrydn, hello Simon Pfeiffer,

sorry that it took me so long to get back to you, I wasn't entirely sure how things will be handled in the future.

First things first:
The development acitvities for this repository will cease. We will move over to a new repository that isn't tied to my personal credentials, but to a KIT-IFL Github account. This will ease the tranistion and onboarding of new members once I leave the institute in the future.

As for your corrections:
I'll look into the pull requests.
